#!/usr/bin/env python3
"""
Quarto pre-render script: strip solutions out of "-solutions.qmd" tutorials.

For every ``*-solutions.qmd`` file in the project, this writes a student
version with the same name minus the "-solutions" suffix, in which every

    :::{.border}
    ...answer...
    :::

block has been removed. Everything else - questions, setup code chunks,
callouts outside a border div - is copied through untouched.

The front matter is reused as-is apart from two changes:

  * ``title`` loses a trailing " (Solutions)"
  * any ``output-file`` loses its "-solutions" suffix, so
    ``tutorial-1-solutions.pdf`` becomes ``tutorial-1.pdf``

Generated files carry a "GENERATED" marker on line 2; the script refuses to
overwrite a file that lacks it, and only rewrites a file when its content
actually changes (so knitr's cache and Quarto's freeze do not fire on every
render).

Usage
-----
    _quarto.yml:
        project:
          pre-render:
            - _prerender.py
            - _pre-render-solutions.py

    python3 _pre-render-solutions.py           # generate
    python3 _pre-render-solutions.py --clean   # delete every generated file
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SOLUTIONS_SUFFIX = "-solutions"           # "tutorial-1-solutions.qmd" -> "tutorial-1.qmd"
SOURCE_GLOB = f"*{SOLUTIONS_SUFFIX}.qmd"

# Div classes whose entire block is removed from the student version.
SOLUTION_CLASSES = (".border",)

# If True the div markers are kept and only their contents are emptied, giving
# students a blank bordered box to write in. If False the block goes entirely.
KEEP_EMPTY_BOX = False

# Removed from the title of the student version (case-insensitive, end of line).
TITLE_STRIP = r"\s*\(Solutions\)\s*$"

SCRIPT_NAME = Path(__file__).name
MARKER = f"# GENERATED BY {SCRIPT_NAME} FROM {{source}} - DO NOT EDIT"
MARKER_RE = re.compile(
    rf"^# GENERATED BY {re.escape(SCRIPT_NAME)} FROM (.+) - DO NOT EDIT\s*$"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FENCE_RE = re.compile(r"^(`{3,}|~{3,})(.*)$")
DIV_RE = re.compile(r"^(:{3,})(.*)$")
CLASS_RES = [re.compile(re.escape(c) + r"(?![\w-])") for c in SOLUTION_CLASSES]

_warnings: list[str] = []
_errors: list[str] = []


def warn(msg: str) -> None:
    _warnings.append(msg)
    print(f"  [warn] {msg}", file=sys.stderr)


def error(msg: str) -> None:
    _errors.append(msg)
    print(f"  [error] {msg}", file=sys.stderr)


def scan_fences(lines: list[str]) -> list[bool]:
    """True for every line that is part of a fenced code block (fence included)."""
    inside = [False] * len(lines)
    fence: tuple[str, int] | None = None
    for i, line in enumerate(lines):
        m = FENCE_RE.match(line.strip())
        if fence is None:
            if m:
                fence = (m.group(1)[0], len(m.group(1)))
                inside[i] = True
        else:
            inside[i] = True
            if (
                m
                and m.group(1)[0] == fence[0]
                and len(m.group(1)) >= fence[1]
                and not m.group(2).strip()
            ):
                fence = None
    return inside


def div_kind(line: str) -> str | None:
    """'open', 'close' or None for a ``:::`` fenced-div line."""
    m = DIV_RE.match(line.rstrip())
    if not m:
        return None
    return "open" if m.group(2).strip() else "close"


def is_solution_div(line: str) -> bool:
    return any(rx.search(line) for rx in CLASS_RES)


def find_div_end(lines: list[str], in_code: list[bool], start: int) -> int | None:
    """Index of the ``:::`` closing the div opened at *start*, honouring nesting."""
    depth = 0
    for i in range(start, len(lines)):
        if in_code[i]:
            continue
        kind = div_kind(lines[i])
        if kind == "open":
            depth += 1
        elif kind == "close":
            depth -= 1
            if depth == 0:
                return i
    return None


def collapse_blank_runs(lines: list[str]) -> list[str]:
    """Squash runs of blank lines outside code blocks down to one."""
    in_code = scan_fences(lines)
    out: list[str] = []
    blanks = 0
    for i, line in enumerate(lines):
        if in_code[i] or line.strip():
            blanks = 0
            out.append(line)
            continue
        blanks += 1
        if blanks == 1:
            out.append(line)
    return out


# ---------------------------------------------------------------------------
# Body
# ---------------------------------------------------------------------------

def strip_solutions(body: str, source: str) -> tuple[str, int]:
    """Remove every solution div. Returns (body, number removed)."""
    lines = body.split("\n")
    in_code = scan_fences(lines)
    out: list[str] = []
    removed = 0

    i = 0
    while i < len(lines):
        line = lines[i]
        if not in_code[i] and div_kind(line) == "open" and is_solution_div(line):
            end = find_div_end(lines, in_code, i)
            if end is None:
                error(f"{source}: unclosed solution div opened on line {i + 1}")
                out.append(line)
                i += 1
                continue
            removed += 1
            if KEEP_EMPTY_BOX:
                out.extend([lines[i], "", lines[end]])
            i = end + 1
            continue
        out.append(line)
        i += 1

    return "\n".join(collapse_blank_runs(out)), removed


# ---------------------------------------------------------------------------
# Front matter
# ---------------------------------------------------------------------------

def split_front_matter(text: str) -> tuple[list[str], str]:
    """Return (yaml lines, body). Missing front matter yields ([], text)."""
    if not text.startswith("---"):
        return [], text
    m = re.match(r"^---[ \t]*\n(.*?)\n(?:---|\.\.\.)[ \t]*\n?(.*)$", text, re.DOTALL)
    if not m:
        return [], text
    return m.group(1).split("\n"), m.group(2)


def strip_quotes(value: str) -> tuple[str, str]:
    """Split a scalar into (quote character or '', inner text)."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[0], value[1:-1]
    return "", value


def rewrite_front_matter(yaml_lines: list[str], source: str) -> list[str]:
    """Copy the front matter, fixing the title and any output-file names."""
    out = [MARKER.format(source=source)]
    seen_title = False

    for line in yaml_lines:
        title = re.match(r"^(title\s*:\s*)(.+?)\s*$", line)
        if title and not seen_title:
            seen_title = True
            quote, text = strip_quotes(title.group(2))
            stripped = re.sub(TITLE_STRIP, "", text, flags=re.IGNORECASE)
            if stripped != text:
                out.append(f"{title.group(1)}{quote}{stripped}{quote}")
                continue

        output_file = re.match(r"^(\s*output-file\s*:\s*)(.+?)\s*$", line)
        if output_file:
            quote, text = strip_quotes(output_file.group(2))
            path = Path(text)
            if path.stem.endswith(SOLUTIONS_SUFFIX):
                stem = path.stem[: -len(SOLUTIONS_SUFFIX)]
                out.append(f"{output_file.group(1)}{quote}{stem}{path.suffix}{quote}")
                continue

        out.append(line)

    if not seen_title:
        warn(f"{source}: no title found in the front matter")
    return out


# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------

def generated_source(path: Path) -> str | None:
    """If *path* was generated by this script, return the source it came from."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            f.readline()                       # opening ---
            m = MARKER_RE.match(f.readline())
    except OSError:
        return None
    return m.group(1) if m else None


def write_if_changed(path: Path, text: str) -> str:
    """Write *text* to *path*: 'created', 'updated', 'unchanged' or 'refused'."""
    if path.exists():
        if generated_source(path) is None:
            error(f"{path}: exists and was not generated by {SCRIPT_NAME} - not overwriting")
            return "refused"
        if path.read_text(encoding="utf-8") == text:
            return "unchanged"
        path.write_text(text, encoding="utf-8", newline="\n")
        return "updated"
    path.write_text(text, encoding="utf-8", newline="\n")
    return "created"


def process(source: Path) -> None:
    text = source.read_text(encoding="utf-8").replace("\r\n", "\n").lstrip("﻿")
    yaml_lines, body = split_front_matter(text)
    if not yaml_lines:
        warn(f"{source.name}: no YAML front matter found")

    stripped, removed = strip_solutions(body, source.name)
    if removed == 0:
        warn(f"{source.name}: no {'/'.join(SOLUTION_CLASSES)} blocks found")

    out_path = source.with_name(source.name[: -len(SOLUTIONS_SUFFIX + ".qmd")] + ".qmd")
    content = (
        "---\n"
        + "\n".join(rewrite_front_matter(yaml_lines, source.name))
        + "\n---\n"
        + stripped.lstrip("\n")
    )
    if not content.endswith("\n"):
        content += "\n"

    status = write_if_changed(out_path, content)
    print(f"    {status:<9} {out_path.name}  ({removed} solution block(s) removed)")


def clean(root: Path) -> None:
    for path in sorted(root.rglob("*.qmd")):
        if generated_source(path):
            path.unlink()
            print(f"  removed {path}")


def selected_sources(root: Path) -> list[Path]:
    """All solution sources, or just those implied by an incremental render."""
    sources = sorted(root.rglob(SOURCE_GLOB))
    if os.environ.get("QUARTO_PROJECT_RENDER_ALL"):
        return sources
    raw = os.environ.get("QUARTO_PROJECT_INPUT_FILES")
    if not raw:
        return sources
    requested = {Path(p.strip()).resolve() for p in raw.splitlines() if p.strip()}
    if not requested:
        return sources
    chosen = []
    for src in sources:
        student = src.with_name(src.name[: -len(SOLUTIONS_SUFFIX + ".qmd")] + ".qmd")
        if {src.resolve(), student.resolve()} & requested:
            chosen.append(src)
    return chosen


def main() -> int:
    root = Path(os.environ.get("QUARTO_PROJECT_DIR", ".")).resolve()

    if "--clean" in sys.argv[1:]:
        clean(root)
        return 0

    sources = selected_sources(root)
    if not sources:
        print(f"No '{SOURCE_GLOB}' files to process.")
        return 0

    for source in sources:
        print(f"{source.relative_to(root)}")
        process(source)

    if _errors:
        print(f"\n{len(_errors)} error(s); pre-render failed.", file=sys.stderr)
        return 1
    print(f"\nDone ({len(sources)} source file(s), {len(_warnings)} warning(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
