#!/usr/bin/env python3
"""
Quarto pre-render script: split "-multi.qmd" lectures into one PDF per language.

For every ``*-multi.qmd`` file in the project, this writes one generated
``.qmd`` per language that appears in the file's language tabsets, keeping only
that language's code. Generated files render to PDF only; the ``-multi.qmd``
source itself is left to render to HTML / revealjs with the tabsets intact.

A "language tabset" is a ``.panel-tabset`` div whose tab headings are language
names (see LANGUAGES). The heading level of the tabs does not matter, and
tabsets whose tabs are not languages (e.g. "Proof" / "Intuition") are copied
through untouched.

Generated files are written *next to their source* so that relative paths in
the document (images, data, ``graph export``) keep working. They carry a
"GENERATED" marker on line 2; the script refuses to overwrite any file that
lacks it, and only rewrites a file when its content actually changes (which
keeps knitr's cache and Quarto's freeze from firing on every render).

Extra metadata set in each generated file, usable with
``::: {.content-visible when-meta="lang-stata"}`` for language-specific prose
that lives outside a tabset:

    multi-lang: stata
    lang-stata: true

Usage
-----
    _quarto.yml:
        project:
          pre-render: _pre-render-multi.py

    python3 _pre-render-multi.py           # generate
    python3 _pre-render-multi.py --clean   # delete every generated file
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Tab label (lower-cased) -> display name. Both run through knitr:
# R chunks natively, Stata chunks via the Statamarkdown package.
LANGUAGES: dict[str, str] = {
    "r": "R",
    "stata": "Stata",
}

MULTI_SUFFIX = "-multi.qmd"
ENGINE_LINE = "engine: knitr"

# PDF options added to the generated file only if the source does not set them.
PDF_DEFAULTS: dict[str, str] = {"toc": "true"}

# Name for the generated PDFs, used only when the source's ``format: pdf:``
# block does not set its own ``output-file``. {base} is the file name without
# "-multi.qmd", {lang} is the language's display name from LANGUAGES above
# ("R", "Stata"). Set to None to let Quarto name the PDF after the generated
# .qmd instead.
PDF_OUTPUT_NAME: str | None = "{base}-notes-{lang}.pdf"

# Name for the generated .qmd files. {lang} is the display name, so the files
# are "lecture-1-R.qmd" / "lecture-1-Stata.qmd". The document metadata keys
# (multi-lang, lang-r, lang-stata) stay lower-cased regardless, since they are
# what ``when-meta`` matches on.
QMD_OUTPUT_NAME = "{base}-{lang}.qmd"

# Format names the generated documents render to. A ``.content-visible`` /
# ``.content-hidden`` div whose when-format / unless-format condition means it
# would not appear in these formats is removed entirely, chunks and all, so
# HTML-only output (DT tables, plotly, ...) never executes during a PDF render.
PDF_FORMATS = {"pdf", "latex", "beamer"}

SUBTITLE_WITH_EXISTING = "{subtitle} ({lang} code)"
SUBTITLE_NEW = "{lang} code"

# Identifies files this script generated. The text is deliberately fixed rather
# than derived from the script's own file name: changing it would make every
# existing generated file unrecognisable, and the script would then refuse to
# overwrite them.
MARKER = "# GENERATED BY _prerender.py FROM {source} - DO NOT EDIT"
MARKER_RE = re.compile(r"^# GENERATED BY _prerender\.py FROM (.+) - DO NOT EDIT\s*$")

# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

FENCE_RE = re.compile(r"^(`{3,}|~{3,})(.*)$")
DIV_RE = re.compile(r"^(:{3,})(.*)$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
FORMAT_COND_RE = re.compile(
    r"\b(when|unless)-format\s*=\s*(?:\"([^\"]*)\"|'([^']*)'|([^\s}]+))"
)
TOP_KEY_RE = re.compile(r"^([A-Za-z0-9_][A-Za-z0-9_.-]*)\s*:(.*)$")

_warnings: list[str] = []
_errors: list[str] = []


def warn(msg: str) -> None:
    _warnings.append(msg)
    print(f"  [warn] {msg}", file=sys.stderr)


def error(msg: str) -> None:
    _errors.append(msg)
    print(f"  [error] {msg}", file=sys.stderr)


def normalise_label(label: str) -> str:
    """'### Stata {.extra}' body -> 'stata'."""
    label = re.sub(r"\{[^}]*\}\s*$", "", label)       # trailing pandoc attributes
    label = label.replace("*", "").replace("`", "")   # emphasis / code ticks
    return label.strip().lower()


def unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def trim_blank_edges(lines: list[str]) -> list[str]:
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


# ---------------------------------------------------------------------------
# Structural parsing (fence-aware, so ``:::`` or ``## x`` inside code is safe)
# ---------------------------------------------------------------------------

def scan_fences(lines: list[str]) -> list[bool]:
    """True for every line that is part of a fenced code block (fence included)."""
    inside = [False] * len(lines)
    fence: tuple[str, int] | None = None
    for i, line in enumerate(lines):
        m = FENCE_RE.match(line.strip())
        if fence is None:
            if m:
                fence = (m.group(1)[0], len(m.group(1)))
                inside[i] = True
        else:
            inside[i] = True
            if (
                m
                and m.group(1)[0] == fence[0]
                and len(m.group(1)) >= fence[1]
                and not m.group(2).strip()
            ):
                fence = None
    return inside


def div_kind(line: str) -> str | None:
    """'open', 'close' or None for a ``:::`` fenced-div line."""
    m = DIV_RE.match(line.rstrip())
    if not m:
        return None
    return "open" if m.group(2).strip() else "close"


def find_div_end(lines: list[str], in_code: list[bool], start: int) -> int | None:
    """Index of the ``:::`` that closes the div opened at *start*."""
    depth = 0
    for i in range(start, len(lines)):
        if in_code[i]:
            continue
        kind = div_kind(lines[i])
        if kind == "open":
            depth += 1
        elif kind == "close":
            depth -= 1
            if depth == 0:
                return i
    return None


def split_tabs(content: list[str], in_code: list[bool]) -> tuple[list[str], list[dict]]:
    """Split a tabset body into (preamble, tabs).

    Tabs are delimited by headings at the level of the *first* heading found at
    the top nesting level of the tabset; deeper headings stay inside their tab.
    """
    preamble: list[str] = []
    tabs: list[dict] = []
    current: dict | None = None
    depth = 0
    tab_level: int | None = None

    for i, line in enumerate(content):
        if not in_code[i]:
            kind = div_kind(line)
            if kind == "open":
                depth += 1
            elif kind == "close":
                depth = max(0, depth - 1)
            elif depth == 0:
                heading = HEADING_RE.match(line)
                if heading:
                    level = len(heading.group(1))
                    if tab_level is None:
                        tab_level = level
                    if level == tab_level:
                        current = {"label": heading.group(2), "lines": []}
                        tabs.append(current)
                        continue
        (current["lines"] if current is not None else preamble).append(line)

    return preamble, tabs


def parse_language_tabsets(lines: list[str], in_code: list[bool], source: str) -> list[dict]:
    """Locate every language tabset in the document."""
    found: list[dict] = []
    i = 0
    while i < len(lines):
        if not in_code[i] and div_kind(lines[i]) == "open" and ".panel-tabset" in lines[i]:
            end = find_div_end(lines, in_code, i)
            if end is None:
                error(f"{source}: unclosed .panel-tabset opened on line {i + 1}")
                return found
            preamble, tabs = split_tabs(lines[i + 1 : end], in_code[i + 1 : end])
            labels = [normalise_label(t["label"]) for t in tabs]
            if any(label in LANGUAGES for label in labels):
                for tab, label in zip(tabs, labels):
                    tab["lang"] = label if label in LANGUAGES else None
                    if tab["lang"] is None:
                        warn(
                            f"{source}: tab '{tab['label'].strip()}' (line {i + 1}) is not a "
                            f"known language and will be dropped from every PDF"
                        )
                found.append({"start": i, "end": end, "preamble": preamble, "tabs": tabs})
            i = end + 1
            continue
        i += 1
    return found


def render_body(lines: list[str], tabsets: list[dict], lang: str, source: str) -> str:
    """Rebuild the body keeping only *lang* inside each language tabset."""
    out: list[str] = []
    cursor = 0
    for ts in tabsets:
        out.extend(lines[cursor : ts["start"]])
        kept = [t for t in ts["tabs"] if t["lang"] == lang]
        if not kept:
            warn(
                f"{source}: tabset on line {ts['start'] + 1} has no "
                f"{LANGUAGES[lang]} tab - nothing kept there in the {LANGUAGES[lang]} PDF"
            )
        block = trim_blank_edges(list(ts["preamble"]))
        for tab in kept:
            if block:
                block.append("")
            block.extend(trim_blank_edges(list(tab["lines"])))
        if block:
            out.extend(block)
            out.append("")
        cursor = ts["end"] + 1
    out.extend(lines[cursor:])
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Conditional content
# ---------------------------------------------------------------------------

def hidden_in_pdf(line: str) -> bool:
    """True for a div whose format condition means it never appears in the PDF.

    Quarto's ``.content-visible`` / ``.content-hidden`` only hide the *output*;
    knitr still executes the chunks inside, so an htmlwidget (DT, plotly, ...)
    meant for HTML or revealjs still runs - and breaks - during a PDF render.
    Dropping those divs outright is the only way to stop that.

    Divs conditioned on metadata rather than format are left alone: their
    condition cannot be evaluated here, and the generated files rely on
    ``when-meta`` for the lang-r / lang-stata switches.
    """
    visible = ".content-visible" in line
    hidden = ".content-hidden" in line
    if not (visible or hidden):
        return False
    if "-meta" in line:
        return False

    m = FORMAT_COND_RE.search(line)
    if not m:
        return False
    value = m.group(2) or m.group(3) or m.group(4) or ""
    formats = {t.lower() for t in re.split(r"[\s,]+", value) if t}
    names_pdf = bool(formats & PDF_FORMATS)

    if visible:
        # visible only when/unless a format: hidden in PDF if PDF isn't included
        return not names_pdf if m.group(1) == "when" else names_pdf
    # content-hidden: the conditions invert
    return names_pdf if m.group(1) == "when" else not names_pdf


def collapse_blank_runs(lines: list[str]) -> list[str]:
    """Squash runs of blank lines outside code blocks down to one."""
    in_code = scan_fences(lines)
    out: list[str] = []
    blanks = 0
    for i, line in enumerate(lines):
        if in_code[i] or line.strip():
            blanks = 0
            out.append(line)
            continue
        blanks += 1
        if blanks == 1:
            out.append(line)
    return out


def strip_pdf_hidden_divs(body: str, source: str) -> tuple[str, int]:
    """Remove every div that the PDF would hide. Returns (body, number removed)."""
    lines = body.split("\n")
    in_code = scan_fences(lines)
    out: list[str] = []
    removed = 0

    i = 0
    while i < len(lines):
        line = lines[i]
        if not in_code[i] and div_kind(line) == "open" and hidden_in_pdf(line):
            end = find_div_end(lines, in_code, i)
            if end is None:
                error(f"{source}: unclosed conditional div opened on line {i + 1}")
                out.append(line)
                i += 1
                continue
            removed += 1
            i = end + 1          # nested divs go with it; find_div_end tracks depth
            continue
        out.append(line)
        i += 1

    return "\n".join(collapse_blank_runs(out)), removed


# ---------------------------------------------------------------------------
# YAML front matter
# ---------------------------------------------------------------------------

def split_front_matter(text: str) -> tuple[list[str], str]:
    """Return (yaml lines, body). Missing front matter yields ([], text)."""
    if not text.startswith("---"):
        return [], text
    m = re.match(r"^---[ \t]*\n(.*?)\n(?:---|\.\.\.)[ \t]*\n?(.*)$", text, re.DOTALL)
    if not m:
        return [], text
    return m.group(1).split("\n"), m.group(2)


def top_level_blocks(yaml_lines: list[str]) -> list[list]:
    """Group front matter into [key, lines] blocks keyed on column-0 entries."""
    blocks: list[list] = []
    current: list | None = None
    for line in yaml_lines:
        starts_block = bool(line.strip()) and not line[0].isspace() and not line.lstrip().startswith("#")
        if starts_block:
            m = TOP_KEY_RE.match(line)
            current = [m.group(1) if m else None, [line]]
            blocks.append(current)
        elif current is None:
            current = [None, [line]]
            blocks.append(current)
        else:
            current[1].append(line)
    return blocks


def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip())


def extract_pdf_options(block_lines: list[str]) -> list[str] | None:
    """Pull the ``pdf:`` sub-options out of a ``format:`` block.

    Returns the option lines (re-indented to 4 spaces), [] if pdf is present
    with no options, or None if the source declares no pdf format at all.
    """
    inline = block_lines[0].split(":", 1)[1].strip()
    if inline:
        return [] if inline.lower() in ("pdf", "[pdf]") else None

    children = block_lines[1:]
    body = [ln for ln in children if ln.strip() and not ln.lstrip().startswith("#")]
    if not body:
        return None
    base = min(indent_of(ln) for ln in body)

    collected: list[str] = []
    capturing = False
    for line in children:
        if not line.strip():
            if capturing:
                collected.append(line)
            continue
        ind = indent_of(line)
        if ind == base:
            m = re.match(r"^\s*([A-Za-z0-9_.-]+)\s*:(.*)$", line)
            key = m.group(1).lower() if m else ""
            if capturing:
                break
            if key == "pdf":
                value = (m.group(2).strip() if m else "")
                if value and value.lower() != "default":
                    return []          # e.g. "pdf: default" or an inline mapping
                capturing = True
            continue
        if capturing and ind > base:
            collected.append(line)

    if not capturing:
        return None
    collected = trim_blank_edges(collected)
    if not collected:
        return []
    shift = 4 - min(indent_of(ln) for ln in collected if ln.strip())
    return [(" " * shift + ln if shift > 0 else ln[-shift:]) if ln.strip() else ln for ln in collected]


def build_format_block(pdf_options: list[str] | None, lang: str, base: str) -> list[str]:
    options = list(pdf_options or [])
    display = LANGUAGES[lang]          # "R" / "Stata", used in the PDF file name

    # Give each language its own output file, otherwise both PDFs collide.
    named = False
    for i, line in enumerate(options):
        m = re.match(r"^(\s*output-file\s*:\s*)(.+?)\s*$", line)
        if m and indent_of(line) == 4:
            stem = Path(unquote(m.group(2)))
            options[i] = f"{m.group(1)}{stem.stem}-{display}{stem.suffix or '.pdf'}"
            named = True
            break
    if not named and PDF_OUTPUT_NAME:
        options.append(f"    output-file: {PDF_OUTPUT_NAME.format(base=base, lang=display)}")

    present = {
        m.group(1).lower()
        for m in (re.match(r"^\s*([A-Za-z0-9_.-]+)\s*:", ln) for ln in options if indent_of(ln) == 4)
        if m
    }
    for key, value in PDF_DEFAULTS.items():
        if key not in present:
            options.insert(0, f"    {key}: {value}")

    if not options:
        return ["format: pdf"]
    return ["format:", "  pdf:"] + options


def build_front_matter(yaml_lines: list[str], lang: str, source: str, base: str) -> list[str]:
    blocks = top_level_blocks(yaml_lines)
    keys = [b[0] for b in blocks]
    display = LANGUAGES[lang]

    pdf_options = None
    for key, lines in blocks:
        if key == "format":
            pdf_options = extract_pdf_options(lines)
    format_block = build_format_block(pdf_options, lang, base)

    out: list[str] = [MARKER.format(source=source)]
    wrote_format = False
    wrote_engine = False

    for key, lines in blocks:
        if key == "format":
            if not wrote_format:
                out.extend(format_block)
                wrote_format = True
        elif key in ("engine", "jupyter"):
            if not wrote_engine:
                out.append(ENGINE_LINE)
                wrote_engine = True
        elif key == "subtitle":
            if len(lines) == 1:
                existing = unquote(lines[0].split(":", 1)[1])
                text = (
                    SUBTITLE_WITH_EXISTING.format(subtitle=existing, lang=display)
                    if existing
                    else SUBTITLE_NEW.format(lang=display)
                )
                out.append(f"subtitle: {yaml_quote(text)}")
            else:
                out.extend(lines)      # multi-line scalar: leave it alone
        else:
            out.extend(lines)
            if key == "title" and "subtitle" not in keys:
                out.append(f"subtitle: {yaml_quote(SUBTITLE_NEW.format(lang=display))}")

    if not wrote_format:
        out.extend(format_block)
    if not wrote_engine:
        out.append(ENGINE_LINE)

    out.append(f"multi-lang: {lang}")
    out.append(f"lang-{lang}: true")
    return out


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

def generated_source(path: Path) -> str | None:
    """If *path* is one of our generated files, return the source it came from."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            f.readline()                       # opening ---
            m = MARKER_RE.match(f.readline())
    except OSError:
        return None
    return m.group(1) if m else None


def match_case_on_disk(path: Path) -> None:
    """Rename a file that differs from *path* only in capitalisation.

    Windows and macOS treat "lecture-1-r.qmd" and "lecture-1-R.qmd" as the same
    file and keep whichever spelling is already on disk, so writing is not
    enough to change the case. Renaming through a temporary name forces it.
    """
    if path.exists() and generated_source(path) is None:
        return                                   # hand-written: leave well alone
    for sibling in path.parent.glob("*.qmd"):
        if sibling.name != path.name and sibling.name.lower() == path.name.lower():
            if generated_source(sibling):
                tmp = sibling.with_name(sibling.name + ".case-tmp")
                sibling.rename(tmp)
                tmp.rename(path)
            return


SIDECAR_SUFFIXES = ("_cache", "_files")


def sync_sidecar_dirs(path: Path) -> None:
    """Keep knitr's "<stem>_cache" / "<stem>_files" folders named after *path*.

    These are keyed on the document's file name. After a rename - including a
    change of capitalisation, which Windows and macOS apply to the file but not
    to the folders beside it - knitr still finds the old cache, restores the
    chunks from it, and never redraws their figures. The "_files" folder is
    then never created and the PDF comes out with no images.
    """
    for suffix in SIDECAR_SUFFIXES:
        want = path.with_name(path.stem + suffix)
        for sibling in path.parent.iterdir():
            if not sibling.is_dir() or sibling.name == want.name:
                continue
            if sibling.name.lower() != want.name.lower():
                continue
            if want.exists() and not os.path.samefile(sibling, want):
                break          # two genuinely distinct folders: don't merge them
            tmp = sibling.with_name(sibling.name + ".case-tmp")
            sibling.rename(tmp)
            tmp.rename(want)
            print(f"    renamed   {sibling.name} -> {want.name}")
            break


def write_if_changed(path: Path, text: str) -> str:
    """Write *text* to *path*. Returns 'created', 'updated', 'unchanged' or 'refused'."""
    match_case_on_disk(path)
    sync_sidecar_dirs(path)
    if path.exists():
        if generated_source(path) is None:
            error(f"{path}: exists and is not a generated file - refusing to overwrite")
            return "refused"
        if path.read_text(encoding="utf-8") == text:
            return "unchanged"
        path.write_text(text, encoding="utf-8", newline="\n")
        return "updated"
    path.write_text(text, encoding="utf-8", newline="\n")
    return "created"


def process(source: Path) -> None:
    text = source.read_text(encoding="utf-8").replace("\r\n", "\n").lstrip("﻿")
    yaml_lines, body = split_front_matter(text)
    if not yaml_lines:
        warn(f"{source.name}: no YAML front matter found")

    lines = body.split("\n")
    tabsets = parse_language_tabsets(lines, scan_fences(lines), source.name)
    if not tabsets:
        warn(f"{source.name}: no language tabsets found - nothing generated")
        return

    languages = sorted({t["lang"] for ts in tabsets for t in ts["tabs"] if t["lang"]})
    print(f"  languages: {', '.join(LANGUAGES[l] for l in languages)}")

    base = source.name[: -len(MULTI_SUFFIX)]
    expected: set[Path] = set()

    for lang in languages:
        out_path = source.with_name(QMD_OUTPUT_NAME.format(base=base, lang=LANGUAGES[lang]))
        expected.add(out_path)
        body_text, dropped = strip_pdf_hidden_divs(
            render_body(lines, tabsets, lang, source.name), source.name
        )
        content = (
            "---\n"
            + "\n".join(build_front_matter(yaml_lines, lang, source.name, base))
            + "\n---\n"
            + body_text.lstrip("\n")
        )
        if not content.endswith("\n"):
            content += "\n"
        note = f"  ({dropped} non-PDF div(s) removed)" if dropped else ""
        print(f"    {write_if_changed(out_path, content):<9} {out_path.name}{note}")

    # Drop files generated for a language this source no longer contains.
    for stale in source.parent.glob(f"{base}-*.qmd"):
        if stale not in expected and generated_source(stale) == source.name:
            stale.unlink()
            print(f"    removed   {stale.name}")
            remove_sidecar_dirs(stale)


def remove_sidecar_dirs(path: Path) -> None:
    """Delete the knitr cache/figure folders belonging to a generated document."""
    for suffix in SIDECAR_SUFFIXES:
        sidecar = path.with_name(path.stem + suffix)
        if sidecar.is_dir():
            shutil.rmtree(sidecar)
            print(f"    removed   {sidecar.name}/")


def clean(root: Path) -> None:
    for path in sorted(root.rglob("*.qmd")):
        if generated_source(path):
            path.unlink()
            print(f"  removed {path}")
            remove_sidecar_dirs(path)


def selected_sources(root: Path) -> list[Path]:
    """All multi sources, or just those implied by an incremental render."""
    sources = sorted(root.rglob(f"*{MULTI_SUFFIX}"))
    if os.environ.get("QUARTO_PROJECT_RENDER_ALL"):
        return sources
    raw = os.environ.get("QUARTO_PROJECT_INPUT_FILES")
    if not raw:
        return sources
    requested = {Path(p.strip()).resolve() for p in raw.splitlines() if p.strip()}
    if not requested:
        return sources
    chosen = []
    for src in sources:
        base = src.name[: -len(MULTI_SUFFIX)]
        siblings = {src.resolve()} | {
            p.resolve() for p in src.parent.glob(f"{base}-*.qmd")
        }
        if siblings & requested:
            chosen.append(src)
    return chosen


def main() -> int:
    root = Path(os.environ.get("QUARTO_PROJECT_DIR", ".")).resolve()

    if "--clean" in sys.argv[1:]:
        clean(root)
        return 0

    sources = selected_sources(root)
    if not sources:
        print(f"No '*{MULTI_SUFFIX}' files to process.")
        return 0

    for source in sources:
        print(f"{source.relative_to(root)}")
        process(source)

    if _errors:
        print(f"\n{len(_errors)} error(s); pre-render failed.", file=sys.stderr)
        return 1
    print(f"\nDone ({len(sources)} source file(s), {len(_warnings)} warning(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
