{
  "hash": "d7676637341f62f6b98fce83c0b26769",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Tutorial 1 (Solutions)\nsubtitle: EC3301 - Martinmas Semester\nformat: \n  html: default\n  pdf: \n    output-file: tutorial-1-solutions.pdf\nengine: npstata\n---\n\n## Statistical inference\n\nConsider a random sample (iid: independently and identitically distributed) drawn from the distribution \n\n$$\n  y_i\\sim N(2,25)\n$$ \n\n1. What is the $E[y_i]$ and $Var(y_i)$?\n\n$$\n  \\begin{aligned}\n  E[y_i] = 2 \\\\\n  Var(y_i) = 25\n  \\end{aligned}\n$$\n\n2. Solve for the expected value and variance of the sample mean: $\\bar{y} = \\frac{1}{n}\\sum_{i=1}^n y_i$.\n\n$$\n  \\begin{aligned}\n  E[\\bar{y}] =& E\\Bigg[\\frac{1}{n}\\sum_{i=1}^n y_i\\Bigg]  \\\\\n  =& \\frac{1}{n}\\sum_{i=1}^n E[y_i] \\\\\n  =& \\frac{1}{n}\\sum_{i=1}^n 2 \\\\\n  =& \\frac{2n}{n} \\\\\n  =& 2\n  \\end{aligned}\n$$\n\n$$\n  \\begin{aligned}\n  Var(\\bar{y}) =& E[(\\bar{y}-\\underbrace{E[\\bar{y}]}_{=2})^2]  \\\\\n  =& E\\Bigg[\\bigg(\\frac{1}{n}\\sum_{i=1}^n (y_i-2)\\bigg)^2\\Bigg] \\\\\n  =& E\\Bigg[\\frac{1}{n^2}\\sum_{i=1}^n (y_i-2)^2+2\\times\\frac{1}{n^2}\\sum_{i=1}^{n-1} \\sum_{j=i+1}^{n} (y_i-2)(y_j-2)\\Bigg] \\\\\n  =& \\frac{1}{n^2}\\sum_{i=1}^n \\underbrace{E\\big[(y_i-2)^2\\big]}_{Var(y_i)} + 2\\times \\sum_{i=1}^{n-1} \\sum_{j=i+1}^{n} \\underbrace{E\\big[(y_i-2)(y_j-2)\\big]}_{Cov(y_i,y_j)=0} \\\\\n  =& \\frac{nVar(y_i)}{n^2} \\\\\n  =& \\frac{25}{n}\n  \\end{aligned}\n$$\n\n3. What is the distribution of $\\bar{y}$?\n\n$$\n  \\bar{y} \\sim N(2,25/n)\n$$\n\n4. Compute the probability that $Pr(\\bar{y}<3)$ in a sample of $n=100$.\n\nSince $\\bar{y} \\sim N(2,1/4)$, \n\n$$\n  \\frac{\\bar{y}-2}{0.5} \\sim N(0,1)\n$$\n\n$$\n  \\begin{aligned}\n  Pr(\\bar{y}<3) =& Pr(\\bar{y}-2<3-2) \\\\\n  =& Pr\\bigg(\\frac{\\bar{y}-2}{0.5} < \\frac{1}{0.5}\\bigg) \\\\\n  =& Pr(z<2)\n  \\end{aligned}\n$$\n\n::: {#ceacb35e .cell execution_count=2}\n``` {.stata .cell-code code-fold=\"true\"}\ndis normal(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRunning C:\\Users\\ndl1\\OneDrive - University of St Andrews\\Documents\\EC3301\\webs\n> ite\\st-andrews-ec3301\\profile.do ...\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style>div.jp-Notebook .datagrid-container {min-height: 448px; }</style>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n.97724987\n```\n:::\n:::\n\n\nSuppose, you draw a random sample that has the following properties. For the next questions we will assume no knowledge of the true mean of $y$; only that it the sample was drawn from a normal distribution $y_i\\sim N(\\mu,\\sigma^2)$ \n\n\n\n::: {#4af6ba3a .cell execution_count=4}\n``` {.stata .cell-code}\nsum y\nmean y\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n           y |        100    2.218156    2.082121   -2.61975   6.654652\n\nMean estimation                            Number of obs = 100\n\n--------------------------------------------------------------\n             |       Mean   Std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n           y |   2.218156   .2082121      1.805018    2.631294\n--------------------------------------------------------------\n```\n:::\n:::\n\n\n5. What is the relationship between the standard deviation of the sample and the standard error of the mean reported above?\n\nThe standard deviation ($s$) is the square-root of the sample variance. The sample variance is an estimate of the unobserved distribution variance ($Var(y_i)=4$). In our above example $s = 2.082121$ which is $\\approx 2 = \\sqrt{4}$. The standard error ($se$) is the square root of the $Var(\\bar{y})$. As we proved above,  $Var(\\bar{y}) = Var(y_i)/n$. That means that $se(\\bar{y}) = sd/\\sqrt{n}$. As $n=100$, we find that $se = .2082121$; exactly equal to the $s/10$.\n\n6. Earlier we showed that, $\\frac{\\bar{y}-2}{se(\\bar{y})} \\sim N(0,1)$ where $se(\\bar{y}) = \\sigma/\\sqrt{n}$. Since we do not know $\\sigma$, what happens to the distribution if we replace $\\sigma$ with $s$, the standard deviation of the sample. \n\n$$\n  \\frac{\\bar{y}-2}{s/\\sqrt{n}} \\sim T_{n-1}\n$$\n\n7. Using the properties of the sample, test the null hypothesis $H_0: \\mu =1.85$ (where $\\mu$ is the unobserved $E[y_i]$). Use a significance level of $\\alpha = 0.05$. \n\n$$\n  \\frac{\\bar{y}-1.85}{s/\\sqrt{n}} \\underset{H_0}{\\sim} T_{n-1}\n$$\n\nCompute the test statistic:\n\n::: {#3de832f8 .cell execution_count=5}\n``` {.stata .cell-code}\ndis (_b[y]-1.85)/_se[y] \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1.7681755\n```\n:::\n:::\n\n\n:::{.callout-note}\nThe `mean` command stores estimates in a similar way to `regress`. They are both e-class commands. \n\n- The `_b[]` function can be used to call the stored coefficient estimate for a particular variable. The full set of coefficients is stored as in the vector `e(b)`. \n- The `_se[]` function can be used to call the SE of a particular coefficient. These computed using the covariance matrix stored as `e(V)`.\n\nTo see the full list of stored estimates, type `ereturn list`. Note, this does not work for `summarize`, which is a r-class command. After summarize you can run `return list` to see the format of its stored estimates. \n:::\n\nRejection rule:\n\n- Since this is a two-sided test, we will reject if $|\\text{test-stat}|<\\text{t}_{99,0.975}$.\n\nThe test static remains the same. \n\nCritical values of t-distribution (which is symmetric):\n\n::: {#7b3bbc90 .cell execution_count=6}\n``` {.stata .cell-code}\ndis invt(99,0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1.984217\n```\n:::\n:::\n\n\nSince $|\\text{test-stat}|<\\text{t}_{99,0.975}$, we fail to reject. \n\n8. Using the properties of the sample, test the null hypothesis $H_0: \\mu \\leq 1.85$.\n\nRejection rule:\n\n- Since this is a one-sided test, we will reject if $\\text{test-stat}>\\text{t}_{99,0.95}$.\n\nCritical values of t-distribution (which is symmetric):\n\n::: {#5cb8dc23 .cell execution_count=7}\n``` {.stata .cell-code}\ndis invt(99,0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1.6603912\n```\n:::\n:::\n\n\nWe reject $H_0$ and conclude that $\\mu > 1.85$. \n\n9. Why is the conclusion different for the two hypotheses?\n\nThe only difference is the critical value. The one-side test has a lower critical value than the two-sided test. \n\n10. Which test has more statistical power? Compute the power of the test to reject $H_0$ when the true value of $\\mu = 2$.\n\nIn the two-sided test:\n\n$$\n  \\begin{aligned}\n  Pr(\\text{Reject}\\;H_0|\\mu = 2) =& Pr\\Bigg(\\bigg|\\frac{\\bar{y}-1.85}{s/\\sqrt{n}}\\bigg|>\\text{t}_{99,0.975}\\Bigg|\\mu = 2\\Bigg) \\\\\n  =& Pr\\Bigg(\\frac{\\bar{y}-1.85}{s/\\sqrt{n}}<\\text{t}_{99,0.025}\\Bigg|\\mu = 2\\Bigg) + Pr\\Bigg(\\frac{\\bar{y}-1.85}{s/\\sqrt{n}}>\\text{t}_{99,0.975}\\Bigg|\\mu = 2\\Bigg) \\\\\n  =& Pr\\Bigg(\\frac{\\bar{y}-2}{s/\\sqrt{n}}<\\text{t}_{99,0.025}-\\frac{0.15}{s/\\sqrt{n}}\\Bigg|\\mu = 2\\Bigg) + Pr\\Bigg(\\frac{\\bar{y}-2}{s/\\sqrt{n}}>\\text{t}_{99,0.975}-\\frac{0.15}{s/\\sqrt{n}}\\Bigg|\\mu = 2\\Bigg) \\\\\n  =& T_{n-1}(\\text{t}_{99,0.025}-\\frac{0.15}{s/\\sqrt{n}}) + 1-T_{n-1}(\\text{t}_{99,0.975}-\\frac{0.15}{s/\\sqrt{n}}) \\\\\n  \\end{aligned}\n$$\n\n::: {#b0d0b21e .cell execution_count=8}\n``` {.stata .cell-code}\ndis t(99,invt(99,0.025)-0.15/_se[y]) + 1 - t(99,invt(99,0.975)-0.15/_se[y])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n.10866073\n```\n:::\n:::\n\n\nIn the one-sided test:\n\n$$\n  \\begin{aligned}\n  Pr(\\text{Reject}\\;H_0|\\mu = 2) =& Pr\\Bigg(\\frac{\\bar{y}-1.85}{s/\\sqrt{n}}>\\text{t}_{99,0.95}\\Bigg|\\mu = 2\\Bigg) \\\\\n  =& Pr\\Bigg(\\frac{\\bar{y}-2}{s/\\sqrt{n}}>\\text{t}_{99,0.95}-\\frac{0.15}{s/\\sqrt{n}}\\Bigg|\\mu = 2\\Bigg) \\\\\n  =& 1-T_{n-1}(\\text{t}_{99,0.95}-\\frac{0.15}{s/\\sqrt{n}}) \\\\\n  \\end{aligned}\n$$\n\n::: {#ea4c72e7 .cell execution_count=9}\n``` {.stata .cell-code}\ndis 1 - t(99,invt(99,0.95)-0.15/_se[y])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n.17475989\n```\n:::\n:::\n\n\nThis shows that the one-sided test is a more powerful test. \n\n## OLS estimator\n\nIn each case, try to prove the following properties of the OLS estimators ($\\hat{\\beta_0},\\hat{\\beta_1}$) for a simple linear regression model\n\n$$\n  y_i = \\beta_0 + \\beta_1 x_i + u_i\n$$\n\na. $\\sum_{i=1}^n \\hat{u}_i=0$, where $\\hat{u}_i = y_i - \\hat{\\beta}_0-\\hat{\\beta}_1 x_i$\n\nb. $\\bar{y} = \\hat{\\beta_0} + \\hat{\\beta_1} \\bar{x}$, where $\\bar{y} = \\frac{1}{n}\\sum_{i=1}^n y_i$ and $\\bar{x} = \\frac{1}{n}\\sum_{i=1}^n x_i$.\n\nc. $\\sum_{i=1}^n x_i \\hat{u}_i = 0$\n\nd. $\\widehat{Cov}(x_i,\\hat{u}_i)=0$ where $\\widehat{Cov}()$ is the sample covariance\n\ne. $\\widehat{Cov(y_i,\\hat{y}_i)} = \\widehat{Var}(x_i)$ where $\\widehat{Var}()$ is the sample variance\n\n## Question 2\n\n\n\n## Question 3\n\n\n\n",
    "supporting": [
      "tutorial-1-solutions_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}