<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 1 (Solutions) – EC3301 Econometrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b651517ce65839d647a86e2780455cfb.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fc741f0b887a700e42f37d64ebb49055.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-cf201e8c159c64e39451d1a718f2f573.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-fc741f0b887a700e42f37d64ebb49055.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">EC3301 Econometrics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lectures" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Lectures</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-lectures">    
        <li>
    <a class="dropdown-item" href="./lecture-0.html">
 <span class="dropdown-text">Pre-sessional Lecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lecture-1.html">
 <span class="dropdown-text">Lecture 1</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./lab-1-Stata.html">
 <span class="dropdown-text">Lab 1 (Stata)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lab-1-R.html">
 <span class="dropdown-text">Lab 1 (R)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extra-material" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Extra Material</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-extra-material">    
        <li>
    <a class="dropdown-item" href="./material-interpretation.html">
 <span class="dropdown-text">Interpreting Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-cef.html">
 <span class="dropdown-text">Conditional Expectation Function</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-programming-R.html">
 <span class="dropdown-text">Basic Programming in R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-programming-Stata.html">
 <span class="dropdown-text">Basic Programming in Stata</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div class="light-content">
<p><img src="img/01-standard-vertical-black-text.png" class="img-fluid"></p>
</div>
<div class="dark-content">
<p><img src="img/02-standard-vertical-white-text.png" class="img-fluid"></p>
</div>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#references" id="toc-references" class="nav-link active" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="tutorial-1-solutions.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 1 (Solutions)</h1>
<p class="subtitle lead">EC3301 - Martinmas Semester</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="statistical-inference" class="level2">
<h2 class="anchored" data-anchor-id="statistical-inference">Statistical inference</h2>
<p>Consider a random sample (iid: independently and identitically distributed) drawn from the distribution</p>
<p><span class="math display">\[
y_i\sim N(2,25)
\]</span></p>
<ol type="1">
<li>What is the <span class="math inline">\(\mu=E[y_i]\)</span> and <span class="math inline">\(\sigma = \sqrt{Var(y_i)}\)</span>?</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \begin{aligned}
  \mu = 2 \\
  \sigma = 5
  \end{aligned}
\]</span></p>
</div>
<ol start="2" type="1">
<li>Solve for the expected value and variance of the sample mean: <span class="math inline">\(\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i\)</span>.</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \begin{aligned}
  E[\bar{y}] =&amp; E\Bigg[\frac{1}{n}\sum_{i=1}^n y_i\Bigg]  \\
  =&amp; \frac{1}{n}\sum_{i=1}^n E[y_i] \\
  =&amp; \frac{1}{n}\sum_{i=1}^n 2 \\
  =&amp; \frac{2n}{n} \\
  =&amp; 2
  \end{aligned}
\]</span></p>
<p><span class="math display">\[
  \begin{aligned}
  Var(\bar{y}) =&amp; E[(\bar{y}-\underbrace{E[\bar{y}]}_{=2})^2]  \\
  =&amp; E\Bigg[\bigg(\frac{1}{n}\sum_{i=1}^n (y_i-2)\bigg)^2\Bigg] \\
  =&amp; E\Bigg[\frac{1}{n^2}\sum_{i=1}^n (y_i-2)^2+2\times\frac{1}{n^2}\sum_{i=1}^{n-1} \sum_{j=i+1}^{n} (y_i-2)(y_j-2)\Bigg] \\
  =&amp; \frac{1}{n^2}\sum_{i=1}^n \underbrace{E\big[(y_i-2)^2\big]}_{Var(y_i)} + 2\times \sum_{i=1}^{n-1} \sum_{j=i+1}^{n} \underbrace{E\big[(y_i-2)(y_j-2)\big]}_{Cov(y_i,y_j)=0} \\
  =&amp; \frac{nVar(y_i)}{n^2} \\
  =&amp; \frac{25}{n}
  \end{aligned}
\]</span></p>
</div>
<ol start="3" type="1">
<li>What is the distribution of <span class="math inline">\(\bar{y}\)</span>?</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \bar{y} \sim N(2,25/n)
\]</span></p>
</div>
<ol start="4" type="1">
<li>Compute the probability that <span class="math inline">\(Pr(\bar{y}&lt;3)\)</span> in a sample of <span class="math inline">\(n=100\)</span>.</li>
</ol>
<div class="border">
<p>Since <span class="math inline">\(\bar{y} \sim N(2,1/4)\)</span>,</p>
<p><span class="math display">\[
  \frac{\bar{y}-2}{0.5} \sim N(0,1)
\]</span></p>
<p><span class="math display">\[
  \begin{aligned}
  Pr(\bar{y}&lt;3) =&amp; Pr(\bar{y}-2&lt;3-2) \\
  =&amp; Pr\bigg(\frac{\bar{y}-2}{0.5} &lt; \frac{1}{0.5}\bigg) \\
  =&amp; Pr(z&lt;2)
  \end{aligned}
\]</span></p>
<div id="d1fba030" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dis <span class="fu">normal</span>(2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.97724987</code></pre>
</div>
</div>
</div>
<p>For the next few questions we will assume no knowledge of the true mean and variance of <span class="math inline">\(y\)</span>; only that the sample was drawn from a normal distribution <span class="math inline">\(y_i\sim N(\mu,\sigma^2)\)</span>. You draw a random sample of 100 observations from this distribution and the sample has the following characteristics:</p>
<div id="1e8fdcb2" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> <span class="fu">y</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
           y |        100    2.218156    2.082121   -2.61975   6.654652</code></pre>
</div>
</div>
<div id="7ec0626d" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">mean</span> <span class="fu">y</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mean estimation                            Number of obs = 100

--------------------------------------------------------------
             |       Mean   Std. err.     [95% conf. interval]
-------------+------------------------------------------------
           y |   2.218156   .2082121      1.805018    2.631294
--------------------------------------------------------------</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>What is the relationship between the standard deviation of the variable and the standard error of the sample mean reported above?</li>
</ol>
<div class="border">
<p>The standard deviation (<span class="math inline">\(s\)</span>) is the square-root of the sample variance. The sample variance (<span class="math inline">\(s^2\)</span>) is an estimate of the unobserved distribution variance (<span class="math inline">\(\sigma^2\)</span>). In this sample, <span class="math inline">\(s = 2.082121\)</span>.</p>
<p>The standard error (<span class="math inline">\(se\)</span>) is the square root of the <span class="math inline">\(Var(\bar{y})\)</span>. As we proved above, <span class="math inline">\(Var(\bar{y}) = \sigma^2/n\)</span>. That means that <span class="math inline">\(se(\bar{y}) = \sigma/\sqrt{n}\)</span>$.</p>
<p>However, we do not know the true value of <span class="math inline">\(\sigma\)</span>. In our estimation of the <span class="math inline">\(se(\bar{y})\)</span>, we replace <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>: <span class="math inline">\(\widehat{se}(\bar{y}) = s/\sqrt{n}\)</span>.</p>
<p>As <span class="math inline">\(n=100\)</span>, we find that <span class="math inline">\(\widehat{se} = 0.2082121\)</span>; exactly equal to the <span class="math inline">\(s/10\)</span>.</p>
</div>
<ol start="6" type="1">
<li>Earlier we showed that, <span class="math inline">\(\frac{\bar{y}-2}{se(\bar{y})} \sim N(0,1)\)</span> where <span class="math inline">\(se(\bar{y}) = \sigma/\sqrt{n}\)</span>. Since we do not know <span class="math inline">\(\sigma\)</span>, what happens to the distribution if we replace <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>, the standard deviation of the sample.</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \frac{\bar{y}-2}{s/\sqrt{n}} \sim T_{n-1}
\]</span></p>
</div>
<ol start="7" type="1">
<li>Using the properties of the sample, test the null hypothesis <span class="math inline">\(H_0: \mu =1.85\)</span>. Use a significance level of <span class="math inline">\(\alpha = 0.05\)</span>.</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \frac{\bar{y}-1.85}{s/\sqrt{n}} \underset{H_0}{\sim} T_{n-1}
\]</span></p>
<p>Compute the test statistic:</p>
<div id="eb00909c" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dis (_b[<span class="fu">y</span>]-1.85)/_se[<span class="fu">y</span>] </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.7681755</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Using stored estimates">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Using stored estimates
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>mean</code> command stores estimates in a similar way to <code>regress</code>. They are both e-class commands.</p>
<ul>
<li>The <code>_b[]</code> function can be used to call the stored coefficient estimate for a particular variable. The full set of coefficients is stored as in the vector <code>e(b)</code>.</li>
<li>The <code>_se[]</code> function can be used to call the SE of a particular coefficient. This is computed using the covariance matrix stored as <code>e(V)</code>.</li>
</ul>
<p>To see the full list of stored estimates, type <code>ereturn list</code>. Note, this does not work for <code>summarize</code>, which is a r-class command. After <code>sum</code> you can run <code>return list</code> to see the format of its stored estimates.</p>
<p>It is good practice to used stored estimates in this way as it prevents typing errors and improves replicability.</p>
</div>
</div>
</div>
<p>Rejection rule:</p>
<ul>
<li>Since this is a two-sided test, we will reject if <span class="math inline">\(|\text{test-stat}|&lt;\text{t}_{99,0.975}\)</span>.</li>
</ul>
<p>The test static remains the same.</p>
<p>Critical values of t-distribution (which is symmetric):</p>
<div id="f32dcd5f" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dis invt(99,0.975)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.984217</code></pre>
</div>
</div>
<p>Since <span class="math inline">\(|\text{test-stat}|&lt;\text{t}_{99,0.975}\)</span>, we fail to reject.</p>
</div>
<ol start="8" type="1">
<li>Using the properties of the sample, test the null hypothesis <span class="math inline">\(H_0: \mu \leq 1.85\)</span>.</li>
</ol>
<div class="border">
<p>Rejection rule:</p>
<ul>
<li>Since this is a one-sided test, we will reject if <span class="math inline">\(\text{test-stat}&gt;\text{t}_{99,0.95}\)</span>.</li>
</ul>
<p>Critical values of t-distribution (which is symmetric):</p>
<div id="5c4bce3a" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dis invt(99,0.95)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.6603912</code></pre>
</div>
</div>
<p>We reject <span class="math inline">\(H_0\)</span> and conclude that <span class="math inline">\(\mu &gt; 1.85\)</span>.</p>
</div>
<ol start="9" type="1">
<li>Why is the conclusion different for the two hypotheses?</li>
</ol>
<div class="border">
<p>The only difference is the critical value. The one-side test has a lower critical value than the two-sided test.</p>
</div>
<ol start="10" type="1">
<li>Which test has more statistical power? Compute the power of the test to reject <span class="math inline">\(H_0\)</span> when the true value of <span class="math inline">\(\mu = 2\)</span>.</li>
</ol>
<div class="border">
<p>In the two-sided test:</p>
<p><span class="math display">\[
  \begin{aligned}
  Pr(\text{Reject}\;H_0|\mu = 2) =&amp; Pr\Bigg(\bigg|\frac{\bar{y}-1.85}{\widehat{se}}\bigg|&gt;\text{t}_{99,0.975}\Bigg|\mu = 2\Bigg) \\
  =&amp; Pr\Bigg(\frac{\bar{y}-1.85}{\widehat{se}}&lt;\text{t}_{99,0.025}\Bigg|\mu = 2\Bigg) + Pr\Bigg(\frac{\bar{y}-1.85}{\widehat{se}}&gt;\text{t}_{99,0.975}\Bigg|\mu = 2\Bigg) \\
  =&amp; Pr\Bigg(\frac{\bar{y}-2}{\widehat{se}}&lt;\text{t}_{99,0.025}-\frac{0.15}{\widehat{se}}\Bigg|\mu = 2\Bigg) \\
  &amp;+ Pr\Bigg(\frac{\bar{y}-2}{\widehat{se}}&gt;\text{t}_{99,0.975}-\frac{0.15}{\widehat{se}}\Bigg|\mu = 2\Bigg) \\
  =&amp; T_{n-1}(\text{t}_{99,0.025}-\frac{0.15}{\widehat{se}}) + 1-T_{n-1}(\text{t}_{99,0.975}-\frac{0.15}{\widehat{se}}) \\
  \end{aligned}
\]</span></p>
<div id="73b669d7" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dis t(99,invt(99,0.025)-0.15/_se[<span class="fu">y</span>]) + 1 - t(99,invt(99,0.975)-0.15/_se[<span class="fu">y</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.10866073</code></pre>
</div>
</div>
<p>In the one-sided test:</p>
<p><span class="math display">\[
  \begin{aligned}
  Pr(\text{Reject}\;H_0|\mu = 2) =&amp; Pr\Bigg(\frac{\bar{y}-1.85}{\widehat{se}}&gt;\text{t}_{99,0.95}\Bigg|\mu = 2\Bigg) \\
  =&amp; Pr\Bigg(\frac{\bar{y}-2}{\widehat{se}}&gt;\text{t}_{99,0.95}-\frac{0.15}{\widehat{se}}\Bigg|\mu = 2\Bigg) \\
  =&amp; 1-T_{n-1}(\text{t}_{99,0.95}-\frac{0.15}{\widehat{se}}) \\
  \end{aligned}
\]</span></p>
<div id="bb05ced7" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dis 1 - t(99,invt(99,0.95)-0.15/_se[<span class="fu">y</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.17475989</code></pre>
</div>
</div>
<p>This shows that the one-sided test is a more powerful test.</p>
</div>
</section>
<section id="the-ols-estimator" class="level2">
<h2 class="anchored" data-anchor-id="the-ols-estimator">The OLS estimator</h2>
<p>In each case, try to prove the following properties of the OLS estimators (<span class="math inline">\(\hat{\beta_0},\hat{\beta_1}\)</span>) for a simple linear regression model</p>
<p><span class="math display">\[
  y_i = \beta_0 + \beta_1 x_i + u_i
\]</span></p>
<ol type="1">
<li><span class="math inline">\(\sum_{i=1}^n \hat{u}_i=0\)</span>, where <span class="math inline">\(\hat{u}_i = y_i - \hat{\beta}_0-\hat{\beta}_1 x_i\)</span></li>
</ol>
<div class="border">
<p>Substitute in the definitions of <span class="math inline">\(\hat{\beta}_0\)</span>:</p>
<p><span class="math display">\[
  \begin{aligned}
    \sum_{i=1}^n \hat{u}_i =&amp; \sum_{i=1}^n \big(y_i - (\bar{y}-\hat{\beta}_1\bar{x})-\hat{\beta}_1 x_i\big) \\
    =&amp; \sum_{i=1}^n\big( (y_i - \bar{y})-\hat{\beta}_1 (x_i-\bar{x})\big) \\
    =&amp; \underbrace{\sum_{i=1}^n (y_i - \bar{y})}_{=0} + \hat{\beta}_1 \underbrace{\sum_{i=1}^n(x_i-\bar{x})}_{=0} \\
    =&amp; 0
  \end{aligned}
\]</span></p>
<p>This demonstrates that the intercept plays an important role in ensuring this result.</p>
</div>
<ol start="2" type="1">
<li><span class="math inline">\(\bar{y} = \hat{\beta_0} + \hat{\beta_1} \bar{x}\)</span>, where <span class="math inline">\(\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i\)</span> and <span class="math inline">\(\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i\)</span>.</li>
</ol>
<div class="border">
<p>This follows from the definition of <span class="math inline">\(\hat{\beta_0}\)</span>, but can also be shown using the decomposition of <span class="math inline">\(y_i = \hat{y}_i + \hat{u}_i\)</span></p>
<p><span class="math display">\[
  \begin{aligned}
    \frac{1}{n}\sum_{i=1}^n y_i =&amp; \frac{1}{n}\sum_{i=1}^n \hat{y}_i + \underbrace{\frac{1}{n}\sum_{i=1}^n\hat{u}_i}_{=0} \\
                                =&amp; \frac{1}{n}\sum_{i=1}^n (\hat{\beta_0} + \hat{\beta_1}x_i) \\
                                =&amp; \hat{\beta_0} + \hat{\beta_1}\frac{1}{n}\underbrace{\sum_{i=1}^n x_i}_{\bar{x}}
  \end{aligned}
\]</span></p>
</div>
<ol start="3" type="1">
<li><span class="math inline">\(\sum_{i=1}^n x_i \hat{u}_i = 0\)</span></li>
</ol>
<div class="border">
<p>Substitute in the definitions of <span class="math inline">\(\hat{u}_i\)</span> from 1.</p>
<p><span class="math display">\[
  \sum_{i=1}^n x_i \hat{u}_i =\sum_{i=1}^n x_i (y_i - \hat{\beta}_0-\hat{\beta}_1 x_i)
\]</span></p>
<p>Now substitue in <span class="math inline">\(\hat{\beta}_0\)</span> and re-arrange</p>
<p><span class="math display">\[
  = \sum_{i=1}^n x_i (y_i - \bar{y}) -\hat{\beta}_1 \sum_{i=1}^nx_i(x_i-\bar{x})
\]</span></p>
<p>Substitute in the definition of <span class="math inline">\(\hat{\beta}_1\)</span></p>
<p><span class="math display">\[
  \begin{aligned}
    =&amp; \sum_{i=1}^n x_i (y_i - \bar{y}) -\frac{\sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})}{\sum_{i=1}^n(x_i-\bar{x})^2} \sum_{i=1}^nx_i(x_i-\bar{x}) \\
    =&amp; 0
  \end{aligned}
\]</span></p>
<p>The result follows from the fact that,</p>
<p><span class="math display">\[
  \sum_{i=1}^n x_i (y_i - \bar{y}) = \sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})
\]</span> and,</p>
<p><span class="math display">\[
  \sum_{i=1}^nx_i(x_i-\bar{x}) = \sum_{i=1}^n(x_i-\bar{x})(x_i-\bar{x})=\sum_{i=1}^n(x_i-\bar{x})^2
\]</span></p>
<p>See Lecture 2 and Wooldridge pp.&nbsp;27 and pp.&nbsp;757.</p>
</div>
<ol start="4" type="1">
<li><span class="math inline">\(\widehat{Cov}(x_i,\hat{u}_i)=0\)</span> where <span class="math inline">\(\widehat{Cov}(\cdot,\cdot)\)</span> is the sample covariance</li>
</ol>
<div class="border">
<p>The result follows directly from 1. and 3.</p>
<p><span class="math display">\[
  \begin{aligned}
    \widehat{Cov}(x_i,\hat{u}_i) =&amp; \frac{1}{n-1}\sum_{i=1}^n(x_i-\bar{x})(\hat{u}_i-\underbrace{\bar{\hat{u}}_i}_{=0}) \\
    =&amp; \frac{1}{n-1}\underbrace{\sum_{i=1}^nx_i\hat{u}_i}_{=0}-\frac{1}{n-1}\sum_{i=1}^n\bar{x}\hat{u}_i \\
    =&amp; -\frac{\bar{x}}{n-1}\underbrace{\sum_{i=1}^n\hat{u}_i}_{=0} \\
    =&amp; 0
  \end{aligned}  
\]</span></p>
<p>Since covariance <span class="math inline">\(=0\)</span> implies correlation <span class="math inline">\(=0\)</span>, we often discuss the result in 3. as the uncorrelatedness of the residual and regressor(s). The result holds for multivariate models too.</p>
</div>
</section>
<section id="application-1-us-worker-wages" class="level2">
<h2 class="anchored" data-anchor-id="application-1-us-worker-wages">Application 1: US worker wages</h2>
<p>One of the most widely estimated regression model in economics is the Mincer equation <span class="citation" data-cites="mincer1974schooling lemieux2006mincer">(<a href="#ref-mincer1974schooling" role="doc-biblioref">Mincer 1974</a>; <a href="#ref-lemieux2006mincer" role="doc-biblioref">Lemieux 2006</a>)</span>. It is a simple linear regression model that regresses log of wages (or earnings) on years of education and a quadratic term in years of <em>potential</em> experience. Where potential experience is measured using years since school completion.</p>
<p><span class="math display">\[
  \ln(wage_i) = \beta_0 + \beta_1 edu_i + \beta_2 exp_i + \beta_3 exp_i^2 + u_i
\]</span></p>
<p>This simple model can be rationalized by a model in which workers choose the length of time the choose to remain in school and delay earning in income in the labour market <span class="citation" data-cites="card2001estimating">(<a href="#ref-card2001estimating" role="doc-biblioref">Card 2001</a>)</span>.</p>
<ol type="1">
<li>Assuming <span class="math inline">\(E[u_i|edu_i,exp_i] = 0\)</span>, solve for <span class="math inline">\(\partial E[\ln(wage_i)|edu_i,exp_i]/\partial exp_i\)</span>. Is the <span class="math inline">\(E[\ln(wage_i)|edu_i,exp_i]\)</span> concave or convex in years of experience?</li>
</ol>
<div class="border">
<p><span class="math display">\[
  \frac{\partial E[\ln(wage_i)|edu_i,exp_i]}{\partial exp_i} = \beta_2 + \beta_3 exp_i
\]</span></p>
<p>The function will be convex (concave) if the second derivate is positive (negative). This then depends on the sign of <span class="math inline">\(\beta_3\)</span>, which is not known.</p>
</div>
<ol start="2" type="1">
<li>Does it make sense to treat education as a continuous variable; i.e.&nbsp;years of education? What alternative approaches could you take?</li>
</ol>
<div class="border">
<p>While one can count the number of years someone spends in education, the learning – or human capital – accumulated through education may not not increase in a linear way with years of education. To account for these non-linearities, you could:</p>
<ol type="1">
<li>add polynomials in the years of education</li>
<li>treat education as a categorical variable</li>
<li>allow for discrete breaks in the relationship; e.g.&nbsp;at high school or UG graduation.</li>
</ol>
</div>
<p>For the remaing questions we are going to use a random sample of the 2024 CPS (Source: <a href="https://data.nber.org/morg/annual/">NBER MORG</a>). The sample includes only male, full-time, workers and excludes self-employed workers. These estimates are based on a random sub-sample of 300 individuals from this dataset.</p>
<ol start="3" type="1">
<li>The plot below shows the average wage for each year of education. Does the relationship appear to be linear in years of education?</li>
</ol>
<div id="7b028efc" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">preserve</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="kw">collapse</span> (<span class="kw">mean</span>) wage, <span class="kw">by</span>(edu)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="kw">scatter</span> wage edu, <span class="bn">ytitle</span>(Average wage) <span class="bn">xtitle</span>(Years <span class="kw">of</span> education)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="kw">restore</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Note: Below code run with echo to enable preserve/restore functionality.)





</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial-1-solutions_files/figure-html/cell-13-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Aggregating data">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Aggregating data
</div>
</div>
<div class="callout-body-container callout-body">
<p>When working with micro-level data (i.e., unit is a firm, individual, household, etc.) you often need to aggregate the data to a lower level (e.g., region, group category). In Stata, this can be done using the <code>collapse</code> command. In R, you can use <code>group_by()</code> function within <code>dplyr</code>. This leads to an irreversible change in the structure of the dataset: you can aggregate data, but not disaggregate it. For this reason, it is a good idea to retain a version of the disaggregated data. In R, this is relatively straight forward because you can assign the aggregated file to a new dataframe. In Stata, you cannot have two datasets open at once. The solution therefore is to <code>preserve</code> a version of the disaggregated data and <code>restore</code> it once you are done with the aggregated file.</p>
<p>Note, <code>preserve</code> and <code>restore</code> must be run together. The command uses temporary files, so if you just run <code>preserve</code> and then later try to <code>restore</code>, the temporary file will no longer exist and you will need to re-open the disaggregated file and reproduce all other changes you made to the dataset.</p>
</div>
</div>
<div class="border">
<p>For parts of the domain (i.e.&nbsp;years of education) the relationship does appear to be linear. This is for years of education from 10-19. Average wages decline beyond 19 and are flat (although noisy) below 10. This may be a sign that level of education matters above a minimum threshold; e.g.&nbsp;completing high school.</p>
</div>
<ol start="4" type="1">
<li>The plot below shows the average <strong>log of</strong> wage for each year of education. Does the relationship appear to be linear in years of education?</li>
</ol>
<div id="4478b384" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">preserve</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="kw">collapse</span> (<span class="kw">mean</span>) lnwage, <span class="kw">by</span>(edu)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="kw">scatter</span> lnwage edu, <span class="bn">ytitle</span>(Average (<span class="fu">log</span> <span class="kw">of</span>) wage) <span class="bn">xtitle</span>(Years <span class="kw">of</span> education)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="kw">restore</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Note: Below code run with echo to enable preserve/restore functionality.)





</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial-1-solutions_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="border">
<p>A similar pattern exists: linear within the domain 10-19 years of education. The log transformation is monotonic, but has a disproportionate impact on larger numbers (e.g.&nbsp;outliers). This may suggest that there are few outliers in the data.</p>
</div>
<p>Below is an estimate of the Mincer equation using the same sub-sample:</p>
<div id="b3d1e14c" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lnwage edu <span class="fu">exp</span> expsq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =       300
-------------+----------------------------------   F(3, 296)       =     33.82
       Model |  26.8176018         3  8.93920059   Prob &gt; F        =    0.0000
    Residual |  78.2323313       296  .264298417   R-squared       =    0.2553
-------------+----------------------------------   Adj R-squared   =    0.2477
       Total |  105.049933       299  .351337569   Root MSE        =     .5141

------------------------------------------------------------------------------
      lnwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         edu |   .0998468   .0107859     9.26   0.000       .07862    .1210736
         exp |   .0208725   .0081481     2.56   0.011      .004837    .0369081
       expsq |  -.0002387    .000162    -1.47   0.142    -.0005575    .0000801
       _cons |   1.732044   .1753344     9.88   0.000     1.386984    2.077104
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Interpret the coefficient on <code>edu</code>.</li>
</ol>
<div class="border">
<p>A 1 year increase in years of education is associated with a <span class="math inline">\(\sim 10\%\)</span> increase in average wages, holding other factors constant. This coefficient is right on the edge of values for which it is appropriate to use the <span class="math inline">\(\hat{\beta}\times 100\)</span> approximation. The exact value is given by,</p>
<div id="e3b66bb6" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dis (<span class="fu">exp</span>(_b[edu])-1)*100</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>10.50016</code></pre>
</div>
</div>
<p>which is slightly higher at 10.5%.</p>
</div>
<ol start="6" type="1">
<li>Ask a LLM to provide an estimate of the returns to an additional year of education from the literature. You must specify that the outcome is measured in log-of wages. What is the typical estimate? And do our estimates seem off?</li>
</ol>
<div class="border">
<p>A query, using Claude, cited a few key studies and meta-analyses. The conclusion was a range of 0.08-0.10; although it did specifiy a lower range of 0.06-0.07 for rich countries. This estimate is therefore slightly higher.</p>
</div>
<ol start="7" type="1">
<li>Can we reject the <span class="math inline">\(H_0: \beta_1 &lt;0.08\)</span> at a <span class="math inline">\(\alpha=0.01\)</span> significance level? What if we chose <span class="math inline">\(\alpha=0.05\)</span> instead?</li>
</ol>
<div class="border">
<p>This test is designed to check whether or model estimates a return to education that is significantly higher than the using 0.08 value. It is a one-sided test, so we will reject if</p>
<p><span class="math display">\[
  \text{test-stat} = \frac{\hat{\beta_1}-0.08}{\widehat{se}(\hat{\beta_1})}&gt;T^{-1}_{300-4}(0.99)
\]</span></p>
<div id="12f16fd3" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dis (_b[edu]-0.08)/_se[edu]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dis invt(<span class="fu">e</span>(df_r),0.99)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>dis invt(<span class="fu">e</span>(df_r),0.95)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.8400626
2.3390116
1.6500177</code></pre>
</div>
</div>
<p>We fail to reject this null hypothesis at 1% significance level. We would reject at a 5% level.</p>
</div>
<ol start="8" type="1">
<li>Test the hypothesis that <span class="math inline">\(H_0:\beta_2=0\)</span> at a <span class="math inline">\(\alpha=0.05\)</span> significance level.</li>
</ol>
<div class="border">
<p>This is a two-sided test. We will reject if,</p>
<p><span class="math display">\[
  |\text{test-stat}| = \Bigg|\frac{\hat{\beta_2}}{\widehat{se}(\hat{\beta_2})}\Bigg|&gt;T^{-1}_{300-4}(0.975)
\]</span></p>
<div id="2ee447df" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dis _b[<span class="fu">exp</span>]/_se[<span class="fu">exp</span>]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dis invt(<span class="fu">e</span>(df_r),0.975)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.56165
1.9680107</code></pre>
</div>
</div>
<p>We reject this null hypothesis.</p>
</div>
<ol start="8" type="1">
<li>Test the hypothesis that <span class="math inline">\(H_0:\beta_3\geq0\)</span> at a <span class="math inline">\(\alpha=0.05\)</span> significance level.</li>
</ol>
<div class="border">
<p>This is a one-sided test. We will reject if,</p>
<p><span class="math display">\[
  \text{test-stat} = \frac{\hat{\beta_3}}{\widehat{se}(\hat{\beta_3})}&lt;T^{-1}_{300-4}(0.05)
\]</span></p>
<div id="7adc4038" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dis _b[expsq]/_se[expsq]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dis invt(<span class="fu">e</span>(df_r),0.05)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>-1.4736091
-1.6500177</code></pre>
</div>
</div>
<p>We fail to reject this null hypothesis.</p>
</div>
<ol start="8" type="1">
<li>Ignoring statistical significance, do the estimates suggest a concave or convex relationship with respect to years of experience?</li>
</ol>
<div class="border">
<p>Since our estimate of <span class="math inline">\(\hat{\beta}_3&lt;0\)</span>, the data suggests that the relationship is concave. Wages are increasing in experience, but at a decreasing rate.</p>
</div>
<ol start="9" type="1">
<li>If we take these estimates seriously, after how many years of experience do we expected wages to decline? Do wages decrease <em>while</em> workers are still working?</li>
</ol>
<div class="border">
<p>For a quadratic function – <span class="math inline">\(y = ax^2 + bx + c\)</span> – the turning point is given by <span class="math inline">\(-b/2a\)</span></p>
<div id="cf991696" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dis -_b[<span class="fu">exp</span>]/(2*_b[expsq])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>43.719251</code></pre>
</div>
</div>
<p>Wages reach their peak around 44 years of experience. This is close to retirement for most workers, so it suggests that wages continue to rise throughout a worker’s career.</p>
</div>
</section>
<section id="application-2-explaining-capital-structures" class="level2">
<h2 class="anchored" data-anchor-id="application-2-explaining-capital-structures">Application 2: Explaining capital structures</h2>
<p>The following model was inspired by <span class="citation" data-cites="frank2009capital">Frank and Goyal (<a href="#ref-frank2009capital" role="doc-biblioref">2009</a>)</span> <a href="https://onlinelibrary.wiley.com/doi/10.1111/j.1755-053X.2009.01026.x"><em>Capital Structure Decisions: Which Factors Are Reliably Important?</em></a>. The authors use a database of publicly-traded (US-listed) firms, from 1950-2003. They have a rich dataset of firm-level and macro-economic variables. In this example, we do not have that. Instead, we have data from the most recent SEC filings for <a href="https://www.sec.gov/data-research/sec-markets-data/financial-statement-data-sets">2026-Q2</a>. Using this smaller cross-sectional dataset, we can estimate the model:</p>
<p><span class="math display">\[
  leverage_i = \beta_0 + \beta_1 size_i + \beta_2 profitability_i + \beta_3 tangibility_i + u_i
\]</span></p>
<p>where,</p>
<ul>
<li><code>leverage</code>: total liabilities divided by total assets</li>
<li><code>size</code>: log of total assets</li>
<li><code>profitability</code>: operating income divided by total assets</li>
<li><code>tangibility</code>: physical assets (e.g., property and equipment) divided by total assets</li>
</ul>
<p>The sample has been restricted to firms with assets of at least $1 million and a tangibility score within <span class="math inline">\([0,1]\)</span>.</p>
<div id="65014e63" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> <span class="kw">leverage</span> <span class="kw">size</span> profitability tangibility</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
    leverage |        271    1.311067    2.914094          0   22.16866
        size |        274     18.3593    2.601397   14.00696   26.29069
profitabil~y |        271    -.673556    2.286625  -29.20916   1.338037
 tangibility |        274    .1079863    .1624912          0   .9984815</code></pre>
</div>
</div>
<div id="4a171c81" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> <span class="kw">leverage</span> <span class="kw">size</span> profitability tangibility</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =       268
-------------+----------------------------------   F(3, 264)       =     29.28
       Model |    572.0114         3  190.670467   Prob &gt; F        =    0.0000
    Residual |  1719.38448       264  6.51282001   R-squared       =    0.2496
-------------+----------------------------------   Adj R-squared   =    0.2411
       Total |  2291.39588       267  8.58200705   Root MSE        =     2.552

------------------------------------------------------------------------------
    leverage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        size |  -.2137509   .0642591    -3.33   0.001    -.3402764   -.0872253
profitabil~y |  -.5102825   .0724029    -7.05   0.000    -.6528431   -.3677218
 tangibility |    .868687   .9541517     0.91   0.363    -1.010029    2.747403
       _cons |   4.792315   1.208169     3.97   0.000     2.413441    7.171188
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<ol type="1">
<li>Interpret the <span class="math inline">\(\mathbf{R}^2\)</span> measure. Is this a high or low value?</li>
</ol>
<div class="border">
<p>The <span class="math inline">\(\mathbf{R}^2=0.2496\)</span>. This tells us that 25% of the variation in the outcome is explained by the model (i.e.&nbsp;the regressors). It is difficult to say whether this is a high or low value, since different variables can be explained more/less by observable regressors. We can say that the value is no smaller than those found in the cited paper, which is somewhat surprising given that the authors include more regressors in their model (and <span class="math inline">\(\mathbf{R}^2\)</span> is weakly increasing in the number of regressors).</p>
</div>
<ol start="2" type="1">
<li>Interpret the <code>_cons</code> coefficient. Does this interpretation relate to a real firm?</li>
</ol>
<div class="border">
<p>Assuming that the error term has conditional mean zero, we can interpret the intercept as <span class="math inline">\(E[y_i|\mathbf{x}_i=0]\)</span>. In this setting, this corresponds to the leverage of a firm with</p>
<ul>
<li><code>size</code><span class="math inline">\(=0\Rightarrow\)</span> total assets of 1.</li>
<li><code>profitability</code><span class="math inline">\(=0\Rightarrow\)</span> zero profits</li>
<li><code>tangibility</code> <span class="math inline">\(=0\Rightarrow\)</span> zero tengible assets</li>
</ul>
<p>There is unlikely to be a firm of this nature in the SEC filings. Some firms may have zero profits, but SEC firms are unlikely to have total assets of $1.</p>
</div>
<ol start="3" type="1">
<li>Interpret each of the slope coefficients. For <code>size</code>, consider a 10% increase in assets. For <code>profitability</code> and <code>tangibility</code>, the regressor is a ratio. Consider the impact of an increase in the ratio of <span class="math inline">\(\Delta x = 0.01\)</span> (or 1%).</li>
</ol>
<div class="border">
<ul>
<li><code>size</code>: a 10% increase in assets increase predicted leverage by</li>
</ul>
<div id="6f81848e" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dis _b[<span class="kw">size</span>]*<span class="fu">ln</span>(1.1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>-.02037263</code></pre>
</div>
</div>
<p>A reduction of 0.02 in leverage, or in 2% in liabilities <em>as a share of assets</em>.</p>
<ul>
<li><code>profitability</code>: a 1% increase in profitability is associated with a -0.51% reduction in leverage (liabilities/assets).</li>
<li><code>tangibility</code>: a 1% increase in tangibility is associated with a 0.87% increase in leverage (liabilities/assets). However, this coefficient is not significantly different from 0.</li>
</ul>
</div>
<ol start="4" type="1">
<li>These results are very different to those of <span class="citation" data-cites="frank2009capital">Frank and Goyal (<a href="#ref-frank2009capital" role="doc-biblioref">2009</a>)</span>. For example, in their Table V the coefficient estimate for tangibility is <span class="math inline">\(0.092\)</span>. What are some of the factors that could explain our vastly different results.</li>
</ol>
<div class="border">
<p>Here are a few factors to consider:</p>
<ul>
<li><p>Time: this is a more recent dataset covering a very different macroeconomic environment. For example, interests have been historically low since the 2008 financial crisis. The authors also pool many years of data.</p></li>
<li><p>Sample selection: the datasets have different sample selection rules, which may lead to a sample representing a very different subset of US firms.</p></li>
<li><p>Model: the authors use a model with many more regressors: firm characteristics and macroeconomic variables not observed in this dataset. The estimates reported here may be effected by the absence of these other regressors. [Note: this is something called omitted variable bias, which we will discuss in Week 8.]</p></li>
</ul>
</div>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-card2001estimating" class="csl-entry" role="listitem">
Card, David. 2001. <span>“Estimating the Return to Schooling: Progress on Some Persistent Econometric Problems.”</span> <em>Econometrica</em> 69 (5): 1127–60.
</div>
<div id="ref-frank2009capital" class="csl-entry" role="listitem">
Frank, Murray Z, and Vidhan K Goyal. 2009. <span>“Capital Structure Decisions: Which Factors Are Reliably Important?”</span> <em>Financial Management</em> 38 (1): 1–37.
</div>
<div id="ref-lemieux2006mincer" class="csl-entry" role="listitem">
Lemieux, Thomas. 2006. <span>“The <span>‘Mincer Equation’</span> Thirty Years After Schooling, Experience, and Earnings.”</span> In <em>Jacob Mincer a Pioneer of Modern Labor Economics</em>, 127–45. Springer.
</div>
<div id="ref-mincer1974schooling" class="csl-entry" role="listitem">
Mincer, Jacob. 1974. <em>Schooling, Experience, and Earnings.</em> New York: Columbia University Press.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>